services:
  - type: web
    name: traffic-management-system
    env: python
    plan: free
    pythonVersion: 3.10
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn traffic_control:app
    envVars:
      - key: FLASK_ENV
        value: production
